### ISSUE TITLE
Image

### ISSUE THREAD

**Issue by sungjk** [DualRTC-io/DualRTC.io#5]
![dual_ubuntu](https://cloud.githubusercontent.com/assets/9454446/10212777/fc498fce-683e-11e5-91c2-cdcd44c8c6ed.png)

![dual_windows](https://cloud.githubusercontent.com/assets/9454446/10213875/501abaac-684d-11e5-9839-a473fc9a9333.png)

![dual_setting_ubuntu](https://cloud.githubusercontent.com/assets/9454446/10213877/56db71ce-684d-11e5-983d-31754c29317b.png)

![dual_setting_windows](https://cloud.githubusercontent.com/assets/9454446/10213880/5dc55ff4-684d-11e5-8746-4f902eae5b26.png)

**Comment by sungjk** [comment]
![logo](https://cloud.githubusercontent.com/assets/9454446/10015785/6695158a-615d-11e5-9103-a80c18ca0769.png)

**Comment by SungjungKim** [comment]
![dual_ubuntu](https://cloud.githubusercontent.com/assets/9454446/10212777/fc498fce-683e-11e5-91c2-cdcd44c8c6ed.png)
